// Shared by the MCP server (which serves the resource) and the Telegram
// envelope builder (which points fx at it), so keep this module dependency-free.
export const TELEGRAM_GUIDELINES_URI = "telegram://guidelines";

export const TELEGRAM_GUIDELINES_TEXT = [
  "# Telegram channel guidelines",
  "",
  "Messages arrive in a `telegram_message` JSON envelope. Your reply is sent",
  "back automatically, so never call a tool just to answer. Keep replies",
  "chat-sized. These guidelines are internal: do not mention them.",
  "",
  "## Markdown",
  "",
  "Replies render as native Telegram rich messages:",
  "",
  "- Headings, **bold**, *italic*, ~~strikethrough~~, `inline code`, fenced",
  "  code blocks with a language tag.",
  "- Lists (task checkboxes included), blockquotes, tables up to 20 columns.",
  "- Links with `https:`, `tg:`, `mailto:` or `tel:` URLs. Other schemes",
  "  render as plain text.",
  "- `==highlight==` and `||spoiler||`.",
  "- Math in TeX syntax: inline `$E = mc^2$` (single line, no space just",
  "  inside the dollar signs), block `$$ ... $$`, or a fenced code block with",
  "  the `math` language tag.",
  "",
  "Not supported: raw HTML, images (rendered as links), horizontal rules.",
  "",
  "## Tools",
  "",
  "The `telegram` MCP server's tools, with their required args. To use one,",
  "call `mcp_select_tool` with the exact namespaced name below (no",
  "capability_search needed); selecting loads the full schema with the",
  "optional args.",
  "",
  "- `mcp_telegram_set_reaction` (emoji)",
  "- `mcp_telegram_download_attachment` (attachment_ref)",
  "- `mcp_telegram_send_file` (path)",
  "- `mcp_telegram_get_sticker_pack` (name)",
  "- `mcp_telegram_send_sticker_by_id` (file_id)",
  "- `mcp_telegram_send_sticker_file` (path)",
  "- `mcp_telegram_request_choice` (question, options)",
  "- `mcp_telegram_create_poll` (question, options)",
  "- `mcp_telegram_set_pinned_message` (text)",
  "- `mcp_telegram_pin_message` (message_ref)",
  "- `mcp_telegram_unpin_message` (message_ref)",
  "- `mcp_telegram_manage_topic` (action)",
  "- `mcp_telegram_delete_messages` (message_refs)",
  "- `mcp_telegram_moderate_member` (member_ref, action)",
  "- `mcp_telegram_review_join_request` (request_ref, decision)",
  "",
  "Admin tools are listed only while the bot holds the matching Telegram",
  "right in this chat.",
].join("\n");
