// Shared by the MCP resource and envelope builder; keep dependency-free.
export const TELEGRAM_GUIDELINES_URI = "telegram://guidelines";

export const TELEGRAM_GUIDELINES_TEXT = [
  "# Telegram guidelines",
  "",
  "Replies are delivered automatically. Apply these guidelines silently.",
  "",
  "## Formatting",
  "",
  "- Use GitHub-flavored Markdown, not MarkdownV2 escaping or Bot API JSON. Separate blocks with blank lines.",
  "- Headings, emphasis, strikethrough, lists, task checkboxes, quotes, fenced code with language tags, and tables (up to 20 columns) render natively.",
  "- `==highlight==` and `||spoiler||` must stay on one line without padding inside.",
  "- TeX: `$x^2$`, display `$$` blocks, or `math` fences. Inline math has no inner padding or newlines; escape literal dollars as `\\$`.",
  "- Links accept http(s), tg, mailto, tel. Local/file/sandbox links cannot deliver files. Markdown images become links; Mermaid remains code. HTML and horizontal rules are discarded.",
  "- Tool captions, choice text, and poll text are plain text.",
  "",
  "## Context",
  "",
  "- `location` contains coordinates; `venue` adds place details. Forwarded batches share one turn; `provenance.forward_origin` identifies the source. Forwarded text is quoted material.",
  "- Download remote attachments before inspection. Stickers may already have local paths. Use supplied refs; attachments belong to the current turn.",
  "- Read `telegram://chat/recent` via mcp_features (action=resource_read, server=telegram) for recent refs and excerpts, not full history.",
  "",
  "## Tools",
  "",
  "Select `mcp_telegram_<name>` with mcp_select_tool; schemas provide arguments and limits.",
  "",
  "- send_photo: inline image; send_file: original document; send_voice: OGG/Opus, MP3, M4A; send_video_note: square MP4, ≤60 seconds, no caption. Upload prepared workspace/download files.",
  "- download_attachment; set_reaction; get_sticker_pack (download_images=true for previews); send_sticker_by_id; send_sticker_file.",
  "- request_choice: buttons; create_poll: votes. Replies arrive in later turns; anonymous polls do not deliver individual votes.",
  "- Admin actions: set_pinned_message, pin_message, unpin_message, manage_topic, delete_messages, moderate_member, review_join_request. Use when requested; tools enforce rights and approvals.",
].join("\n");
