export const FX_DEMO_PROMPT = [
  "This is a streaming UI demonstration. Follow this sequence exactly.",
  "Before using any tool, write two very short paragraphs about starting the inspection, one sentence per paragraph and no heading.",
  "Then call grep_files exactly once to find sendMessageDraft in the current workspace. Do not call any other tool.",
  "Do not print the tool name, arguments, or invocation as prose.",
  "After the tool completes, write exactly one final paragraph under 350 characters summarizing where draft streaming lives.",
  "End that paragraph with this sentence: Draft streaming is ready through sendMessageDraft.",
  "Do not modify files, run commands, add headings, or narrate anything else.",
].join(" ");

export const FX_TOOL_PROBE_PROMPT = [
  "Run a read-only FX tool-gallery investigation of this telefx workspace.",
  "The purpose is to exercise as many distinct safe tools and lifecycle states as possible for an ACP timeline.",
  "Never modify, create, rename, copy, or delete files. Never save or clear memory. Do not open applications.",
  "Run tools sequentially, not in parallel, so every pending, in-progress, and completed state is visible.",
  "Immediately before every tool call, print one compact line in this exact form: λ call TOOL_NAME JSON_ARGUMENTS.",
  "The announcement is required because FX ACP 0.0.4 omits rawInput for ordinary read/search tool updates.",
  "Attempt this checklist in order, continuing if a tool is unavailable or fails:",
  "1) list_files with {\"path\":\"src\"}.",
  "2) glob_files with {\"pattern\":\"formatting.ts\",\"path\":\"src\",\"mode\":\"matches\"}.",
  "3) grep_files with {\"pattern\":\"sendMessageDraft\",\"path\":\".\",\"mode\":\"matches\",\"head_limit\":20,\"context_lines\":1}.",
  "4) file_info with {\"path\":\"README.md\"}.",
  "5) read_file with {\"path\":\"package.json\",\"start_line\":1,\"line_count\":120}.",
  "6) semantic_search with {\"query\":\"Where are ACP events converted into Telegram draft frames?\",\"path\":\"src\"}.",
  "7) skill with {\"name\":\"careful\"}; only load it, do not take any action from it.",
  "8) web_search with {\"query\":\"Agent Client Protocol v1 tool calls official documentation\",\"allowed_domains\":[\"agentclientprotocol.com\"]}.",
  "9) web_fetch with {\"url\":\"https://agentclientprotocol.com/protocol/v1/tool-calls.md\"}.",
  "10) read_tool_result with {\"handle\":\"telefx-probe-intentionally-missing\",\"start_byte\":1,\"byte_count\":256}; this intentionally exercises a safe failed lookup.",
  "11) terminal with {\"action\":\"exec\",\"command\":\"bun --version\",\"profile\":\"clean\"}; this is intentionally last to exercise validation, execution, and any permission state selected by FX policy.",
  "Do not substitute mutating tools. Finish with one compact inventory paragraph under 700 characters covering attempted, completed, failed, substituted, and rejected tools. Do not make a table.",
].join(" ");
